version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nextjs:
    build: .
    container_name: ecommerce_nextjs
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./src/app:/app

volumes:
  postgres_data: