
services:
  postgres:
    image: postgres:14
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgrespassword}
      POSTGRES_DB: ${POSTGRES_DB:-ecommerce}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./populate-db.sh:/populate-db.sh
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  # bun:
  #   image: oven/bun:1
  #   volumes:
  #     - ./scripts:/app/scripts
  #     - ./tsconfig.json:/app/tsconfig.json
  #   environment:
  #     DATABASE_URL: postgresql://${APP_USER}:${APP_PASSWORD}@postgres:5432/${POSTGRES_DB}
  #   networks:
  #     - postgres_network
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
